name: learn-github-actions
run-name: ${{ github.actor }} Regression
on: [push]
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y --no-install-recommends iverilog
      - run: pip3 install cocotb cocotb_coverage cocotb_bus
      - run: make -C test
      - uses: actions/upload-artifact@v3
        with:
          name: waveform
          path: test/*.vcd
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/test/results.xml'
